// <auto-generated />
using System;
using BanCaPheNuocGiaiKhat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BanCaPheNuocGiaiKhat.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616003226_AddOrdersItemsInvoices")]
    partial class AddOrdersItemsInvoices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BanCaPheNuocGiaiKhat.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentId");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Cà phê hạt"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Cà phê bột"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Dụng cụ pha chế"
                        });
                });

            modelBuilder.Entity("BanCaPheNuocGiaiKhat.Models.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<decimal>("CashGiven")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cash_given");

                    b.Property<decimal>("ChangeAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("change_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("InvoiceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("invoice_code");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime")
                        .HasColumnName("paid_at");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("InvoiceId");

                    b.HasIndex("InvoiceCode")
                        .IsUnique();

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("BanCaPheNuocGiaiKhat.Models.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<decimal?>("CashGiven")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cash_given");

                    b.Property<decimal?>("ChangeAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("change_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("notes");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("staff_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("OrderId");

                    b.HasIndex("StaffId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("BanCaPheNuocGiaiKhat.Models.Entities.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("BanCaPheNuocGiaiKhat.Models.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_price");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DetailDesc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail_desc");

                    b.Property<string>("GrindType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("grind_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<decimal?>("PromotionPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("promotion_price");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("region");

                    b.Property<string>("RoastLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("roast_level");

                    b.Property<string>("ShortDesc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("short_desc");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<int>("StockQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_qty");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("view_count");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            BasePrice = 22.00m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Ethiopian Yirgacheffe coffee is dry-processed, bringing out the bright, clean taste profile. Notes of citrus and floral aromas are dominant.",
                            GrindType = "whole-bean",
                            Name = "Ethiopia Yirgacheffe",
                            Region = "africa",
                            RoastLevel = "light",
                            ShortDesc = "Floral notes with hints of jasmine and bright citrus. Light roast.",
                            Slug = "ethiopia-yirgacheffe",
                            Status = "active",
                            StockQty = 50,
                            ThumbnailUrl = "/images/product-ethiopian.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 12
                        },
                        new
                        {
                            ProductId = 2,
                            BasePrice = 19.50m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Colombia Supremo beans are carefully selected and roasted to a medium profile to balance the natural acidity with nutty tones.",
                            GrindType = "whole-bean",
                            Name = "Colombia Supremo",
                            Region = "south-america",
                            RoastLevel = "medium",
                            ShortDesc = "Smooth, balanced body with caramel sweetness and a nutty finish. Medium roast.",
                            Slug = "colombia-supremo",
                            Status = "active",
                            StockQty = 35,
                            ThumbnailUrl = "/images/product-colombia.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 8
                        },
                        new
                        {
                            ProductId = 3,
                            BasePrice = 21.00m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Sumatra Mandheling coffee is known for its heavy body and low acidity, featuring unique cedar wood and herbal notes.",
                            GrindType = "whole-bean",
                            Name = "Sumatra Mandheling",
                            Region = "asia-pacific",
                            RoastLevel = "dark",
                            ShortDesc = "Full-bodied, earthy, and complex with low acidity. Dark roast.",
                            Slug = "sumatra-mandheling",
                            Status = "active",
                            StockQty = 40,
                            ThumbnailUrl = "/images/hero-coffee-beans.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 20
                        },
                        new
                        {
                            ProductId = 4,
                            BasePrice = 24.00m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Our signature espresso blend combines beans from South America and Africa, roasted dark to bring out rich cocoa and toasted nut flavors.",
                            GrindType = "whole-bean",
                            Name = "Artisan Espresso Blend",
                            Region = "south-america",
                            RoastLevel = "espresso",
                            ShortDesc = "Rich crema, notes of dark chocolate and toasted almonds. Espresso roast.",
                            Slug = "artisan-espresso-blend",
                            Status = "active",
                            StockQty = 25,
                            ThumbnailUrl = "/images/product-artisan-espresso.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 15
                        },
                        new
                        {
                            ProductId = 5,
                            BasePrice = 20.50m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Guatemala Antigua beans are grown in volcanic soil, resulting in a unique smoky flavor combined with a light citrus brightness.",
                            GrindType = "whole-bean",
                            Name = "Guatemala Antigua",
                            Region = "central-america",
                            RoastLevel = "medium",
                            ShortDesc = "Spicy and smoky undertones with a crisp apple acidity. Medium roast.",
                            Slug = "guatemala-antigua",
                            Status = "active",
                            StockQty = 30,
                            ThumbnailUrl = "/images/product-guatemala.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 5
                        },
                        new
                        {
                            ProductId = 6,
                            BasePrice = 23.50m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Kenya AA is processed using wet method, offering an exceptionally intense and clean cup.",
                            GrindType = "whole-bean",
                            Name = "Kenya AA",
                            Region = "africa",
                            RoastLevel = "light",
                            ShortDesc = "Bright acidity with blackcurrant and berry notes.",
                            Slug = "kenya-aa",
                            Status = "active",
                            StockQty = 45,
                            ThumbnailUrl = "/images/product-ethiopian.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 28
                        },
                        new
                        {
                            ProductId = 7,
                            BasePrice = 18.00m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Classic Brazilian coffee bean, roasted to highlight its natural sweetness.",
                            GrindType = "whole-bean",
                            Name = "Brazil Santos",
                            Region = "south-america",
                            RoastLevel = "medium",
                            ShortDesc = "Low acidity, smooth body with sweet chocolate notes.",
                            Slug = "brazil-santos",
                            Status = "active",
                            StockQty = 60,
                            ThumbnailUrl = "/images/product-colombia.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 33
                        },
                        new
                        {
                            ProductId = 8,
                            BasePrice = 20.00m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Tarrazu region provides one of the finest beans in Central America.",
                            GrindType = "whole-bean",
                            Name = "Costa Rica Tarrazu",
                            Region = "central-america",
                            RoastLevel = "medium",
                            ShortDesc = "Crisp acidity with sweet honey and citrus flavors.",
                            Slug = "costa-rica-tarrazu",
                            Status = "active",
                            StockQty = 25,
                            ThumbnailUrl = "/images/product-guatemala.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 19
                        },
                        new
                        {
                            ProductId = 9,
                            BasePrice = 21.50m,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Ground Ethiopian Sidamo coffee ready for drip brewing.",
                            GrindType = "medium",
                            Name = "Ethiopian Sidamo Ground",
                            Region = "africa",
                            RoastLevel = "light",
                            ShortDesc = "Floral aroma with notes of lemon and cane sugar.",
                            Slug = "ethiopian-sidamo-ground",
                            Status = "active",
                            StockQty = 30,
                            ThumbnailUrl = "/images/product-ethiopian.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 14
                        },
                        new
                        {
                            ProductId = 10,
                            BasePrice = 19.00m,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Ground French roast ideal for French Press brewing.",
                            GrindType = "coarse",
                            Name = "French Roast Blend",
                            Region = "south-america",
                            RoastLevel = "dark",
                            ShortDesc = "Intensely dark and smoky with a heavy body.",
                            Slug = "french-roast-blend",
                            Status = "active",
                            StockQty = 40,
                            ThumbnailUrl = "/images/hero-coffee-beans.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 11
                        },
                        new
                        {
                            ProductId = 11,
                            BasePrice = 19.50m,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Fine ground Italian roast optimized for espresso machines.",
                            GrindType = "fine",
                            Name = "Italian Roast Espresso Ground",
                            Region = "south-america",
                            RoastLevel = "espresso",
                            ShortDesc = "Rich, dark roast optimized for espresso brewing.",
                            Slug = "italian-roast-espresso-ground",
                            Status = "active",
                            StockQty = 50,
                            ThumbnailUrl = "/images/product-artisan-espresso.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 22
                        },
                        new
                        {
                            ProductId = 12,
                            BasePrice = 25.00m,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Premium Japanese ceramic pour-over dripper.",
                            Name = "Hario V60 Ceramic",
                            ShortDesc = "Classic ceramic coffee dripper for pour-over brewing.",
                            Slug = "hario-v60-ceramic",
                            Status = "active",
                            StockQty = 20,
                            ThumbnailUrl = "/images/category-accessories.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 9
                        },
                        new
                        {
                            ProductId = 13,
                            BasePrice = 45.00m,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Chemex glass coffeemaker with wood collar and leather tie.",
                            Name = "Chemex 6-Cup",
                            ShortDesc = "Elegant glass coffee maker for clean and pure flavor.",
                            Slug = "chemex-6-cup",
                            Status = "active",
                            StockQty = 15,
                            ThumbnailUrl = "/images/category-accessories.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 18
                        },
                        new
                        {
                            ProductId = 14,
                            BasePrice = 39.99m,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Aeropress travel version with convenient mug/carrying case.",
                            Name = "Aeropress Go",
                            ShortDesc = "Compact coffee press for travel and convenience.",
                            Slug = "aeropress-go",
                            Status = "active",
                            StockQty = 25,
                            ThumbnailUrl = "/images/category-accessories.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 25
                        },
                        new
                        {
                            ProductId = 15,
                            BasePrice = 22.50m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Java Preanger beans from West Java volcanic highlands.",
                            GrindType = "whole-bean",
                            Name = "Java Preanger",
                            Region = "asia-pacific",
                            RoastLevel = "medium",
                            ShortDesc = "Traditional Indonesian cup with sweet herbal nuances.",
                            Slug = "java-preanger",
                            Status = "active",
                            StockQty = 30,
                            ThumbnailUrl = "/images/hero-coffee-beans.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 7
                        },
                        new
                        {
                            ProductId = 16,
                            BasePrice = 16.50m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Buon Ma Thuot high-grade robusta beans with strong flavor.",
                            GrindType = "whole-bean",
                            Name = "Vietnam Robusta Special",
                            Region = "asia-pacific",
                            RoastLevel = "dark",
                            ShortDesc = "Bold, high-caffeine Robusta beans from Buon Ma Thuot.",
                            Slug = "vietnam-robusta-special",
                            Status = "active",
                            StockQty = 80,
                            ThumbnailUrl = "/images/product-colombia.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 42
                        },
                        new
                        {
                            ProductId = 17,
                            BasePrice = 19.90m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Single origin Peru coffee beans.",
                            GrindType = "whole-bean",
                            Name = "Peru Cajamarca",
                            Region = "south-america",
                            RoastLevel = "medium",
                            ShortDesc = "Mellow body with subtle apple acidity and caramel notes.",
                            Slug = "peru-cajamarca",
                            Status = "active",
                            StockQty = 35,
                            ThumbnailUrl = "/images/product-guatemala.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 13
                        },
                        new
                        {
                            ProductId = 18,
                            BasePrice = 17.50m,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Ground house blend of South American and African beans.",
                            GrindType = "medium",
                            Name = "House Blend Ground",
                            Region = "south-america",
                            RoastLevel = "medium",
                            ShortDesc = "Our balanced house blend for everyday brewing.",
                            Slug = "house-blend-ground",
                            Status = "active",
                            StockQty = 70,
                            ThumbnailUrl = "/images/product-artisan-espresso.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 16
                        },
                        new
                        {
                            ProductId = 19,
                            BasePrice = 35.00m,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Bialetti Moka Express 3-Cup stovetop espresso maker.",
                            Name = "Moka Pot Bialetti",
                            ShortDesc = "Iconic Italian stovetop espresso maker.",
                            Slug = "moka-pot-bialetti",
                            Status = "active",
                            StockQty = 18,
                            ThumbnailUrl = "/images/category-accessories.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 21
                        },
                        new
                        {
                            ProductId = 20,
                            BasePrice = 30.00m,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Kalita Wave stainless steel 185 pour-over dripper.",
                            Name = "Kalita Wave Stainless",
                            ShortDesc = "Flat-bottom coffee dripper for even extraction.",
                            Slug = "kalita-wave-stainless",
                            Status = "active",
                            StockQty = 12,
                            ThumbnailUrl = "/images/category-accessories.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 10
                        },
                        new
                        {
                            ProductId = 21,
                            BasePrice = 55.00m,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Porlex Mini stainless steel hand coffee grinder with ceramic burrs.",
                            Name = "Porlex Mini Grinder",
                            ShortDesc = "Portable ceramic burr hand grinder.",
                            Slug = "porlex-mini-grinder",
                            Status = "active",
                            StockQty = 10,
                            ThumbnailUrl = "/images/category-accessories.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 31
                        },
                        new
                        {
                            ProductId = 22,
                            BasePrice = 40.00m,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Stovetop gooseneck kettle for precise water flow control.",
                            Name = "Gooseneck Kettle",
                            ShortDesc = "Stainless steel kettle with precise pour control.",
                            Slug = "gooseneck-kettle",
                            Status = "active",
                            StockQty = 15,
                            ThumbnailUrl = "/images/category-accessories.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 17
                        },
                        new
                        {
                            ProductId = 23,
                            BasePrice = 65.00m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Authentic Jamaica Blue Mountain coffee with a smooth, clean finish.",
                            GrindType = "whole-bean",
                            Name = "Jamaica Blue Mountain",
                            Region = "caribbean",
                            RoastLevel = "medium",
                            ShortDesc = "Mild flavor, lack of bitterness, and sweet herbal notes.",
                            Slug = "jamaica-blue-mountain",
                            Status = "active",
                            StockQty = 10,
                            ThumbnailUrl = "/images/product-guatemala.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 50
                        },
                        new
                        {
                            ProductId = 24,
                            BasePrice = 55.00m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Grown on the slopes of Hualalai and Mauna Loa in the North and South Kona Districts.",
                            GrindType = "whole-bean",
                            Name = "Hawaii Kona Extra Fancy",
                            Region = "hawaii",
                            RoastLevel = "medium",
                            ShortDesc = "Rich, smooth, and deeply flavorful with a nutty aroma.",
                            Slug = "hawaii-kona-extra-fancy",
                            Status = "active",
                            StockQty = 15,
                            ThumbnailUrl = "/images/product-colombia.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 45
                        },
                        new
                        {
                            ProductId = 25,
                            BasePrice = 24.00m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Peaberry coffee beans from the slopes of Mount Kilimanjaro.",
                            GrindType = "whole-bean",
                            Name = "Tanzania Peaberry",
                            Region = "africa",
                            RoastLevel = "light",
                            ShortDesc = "Bright acidity with notes of blackcurrant and chocolate.",
                            Slug = "tanzania-peaberry",
                            Status = "active",
                            StockQty = 25,
                            ThumbnailUrl = "/images/product-ethiopian.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 12
                        },
                        new
                        {
                            ProductId = 26,
                            BasePrice = 21.00m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Bourbon varietal grown in the high altitudes of Rwanda.",
                            GrindType = "whole-bean",
                            Name = "Rwanda Bourbon",
                            Region = "africa",
                            RoastLevel = "medium",
                            ShortDesc = "Sweet with floral notes and hints of caramelized sugar.",
                            Slug = "rwanda-bourbon",
                            Status = "active",
                            StockQty = 30,
                            ThumbnailUrl = "/images/hero-coffee-beans.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 20
                        },
                        new
                        {
                            ProductId = 27,
                            BasePrice = 22.00m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Sourced from the Ngozi province, featuring bright and juicy fruit notes.",
                            GrindType = "whole-bean",
                            Name = "Burundi Ngozi",
                            Region = "africa",
                            RoastLevel = "light",
                            ShortDesc = "Complex fruit flavors with a clean, sweet finish.",
                            Slug = "burundi-ngozi",
                            Status = "active",
                            StockQty = 20,
                            ThumbnailUrl = "/images/product-colombia.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 18
                        },
                        new
                        {
                            ProductId = 28,
                            BasePrice = 35.00m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "One of the oldest and most traditional coffees, grown on dry terraces in Yemen.",
                            GrindType = "whole-bean",
                            Name = "Yemen Mocha Mattari",
                            Region = "middle-east",
                            RoastLevel = "medium",
                            ShortDesc = "Earthy, complex with intense chocolate and wine notes.",
                            Slug = "yemen-mocha-mattari",
                            Status = "active",
                            StockQty = 12,
                            ThumbnailUrl = "/images/product-artisan-espresso.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 35
                        },
                        new
                        {
                            ProductId = 29,
                            BasePrice = 85.00m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "A highly sought-after, premium coffee varietal known for its tea-like body and floral aroma.",
                            GrindType = "whole-bean",
                            Name = "Panama Geisha",
                            Region = "central-america",
                            RoastLevel = "light",
                            ShortDesc = "Incredibly delicate with jasmine aroma and bergamot flavors.",
                            Slug = "panama-geisha",
                            Status = "active",
                            StockQty = 5,
                            ThumbnailUrl = "/images/product-guatemala.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 80
                        },
                        new
                        {
                            ProductId = 30,
                            BasePrice = 20.00m,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Processed using the Swiss Water Method to retain 99.9% of the flavor without the caffeine.",
                            GrindType = "whole-bean",
                            Name = "Decaf Swiss Water Blend",
                            Region = "south-america",
                            RoastLevel = "medium",
                            ShortDesc = "Smooth and rich, decaffeinated without chemicals.",
                            Slug = "decaf-swiss-water",
                            Status = "active",
                            StockQty = 40,
                            ThumbnailUrl = "/images/hero-coffee-beans.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 15
                        },
                        new
                        {
                            ProductId = 31,
                            BasePrice = 16.00m,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "A perfectly balanced blend of South American and Central American beans.",
                            GrindType = "medium",
                            Name = "Breakfast Blend Ground",
                            Region = "blend",
                            RoastLevel = "medium",
                            ShortDesc = "A bright, crisp start to the day.",
                            Slug = "breakfast-blend-ground",
                            Status = "active",
                            StockQty = 60,
                            ThumbnailUrl = "/images/product-colombia.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 22
                        },
                        new
                        {
                            ProductId = 32,
                            BasePrice = 17.00m,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Premium ground coffee infused with natural vanilla and hazelnut flavors.",
                            GrindType = "medium",
                            Name = "Vanilla Nut Ground",
                            Region = "blend",
                            RoastLevel = "medium",
                            ShortDesc = "Sweet vanilla and toasted nut aromas.",
                            Slug = "vanilla-nut-ground",
                            Status = "active",
                            StockQty = 45,
                            ThumbnailUrl = "/images/product-artisan-espresso.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 30
                        },
                        new
                        {
                            ProductId = 33,
                            BasePrice = 17.00m,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Smooth and aromatic ground coffee with a distinctive hazelnut cream finish.",
                            GrindType = "medium",
                            Name = "Hazelnut Cream Ground",
                            Region = "blend",
                            RoastLevel = "medium",
                            ShortDesc = "Rich, buttery hazelnut flavor.",
                            Slug = "hazelnut-cream-ground",
                            Status = "active",
                            StockQty = 40,
                            ThumbnailUrl = "/images/product-guatemala.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 28
                        },
                        new
                        {
                            ProductId = 34,
                            BasePrice = 19.00m,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "A dark roasted blend ground coarsely for the perfect, smooth cold brew at home.",
                            GrindType = "coarse",
                            Name = "Cold Brew Coarse Ground",
                            Region = "blend",
                            RoastLevel = "dark",
                            ShortDesc = "Specially ground for cold water extraction.",
                            Slug = "cold-brew-coarse-ground",
                            Status = "active",
                            StockQty = 55,
                            ThumbnailUrl = "/images/hero-coffee-beans.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 42
                        },
                        new
                        {
                            ProductId = 35,
                            BasePrice = 28.00m,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "1 Liter capacity French press for a full-bodied coffee experience.",
                            Name = "French Press Maker (1L)",
                            ShortDesc = "Classic glass French Press with stainless steel filter.",
                            Slug = "french-press-maker-1l",
                            Status = "active",
                            StockQty = 25,
                            ThumbnailUrl = "/images/category-accessories.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 18
                        },
                        new
                        {
                            ProductId = 36,
                            BasePrice = 22.00m,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Accurate up to 0.1g, perfect for pour-over and espresso dialing in.",
                            Name = "Digital Coffee Scale",
                            ShortDesc = "Precision scale with built-in timer.",
                            Slug = "digital-coffee-scale",
                            Status = "active",
                            StockQty = 30,
                            ThumbnailUrl = "/images/category-accessories.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 34
                        },
                        new
                        {
                            ProductId = 37,
                            BasePrice = 18.00m,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Sturdy plastic knock box with a removable rubber bar for easy cleaning.",
                            Name = "Coffee Knock Box",
                            ShortDesc = "Durable knock box for espresso pucks.",
                            Slug = "coffee-knock-box",
                            Status = "active",
                            StockQty = 40,
                            ThumbnailUrl = "/images/category-accessories.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 12
                        },
                        new
                        {
                            ProductId = 38,
                            BasePrice = 15.00m,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Classic stainless steel pitcher with a precision spout for pouring latte art.",
                            Name = "Milk Frothing Pitcher",
                            ShortDesc = "Stainless steel pitcher (350ml) for latte art.",
                            Slug = "milk-frothing-pitcher",
                            Status = "active",
                            StockQty = 50,
                            ThumbnailUrl = "/images/category-accessories.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 21
                        },
                        new
                        {
                            ProductId = 39,
                            BasePrice = 25.00m,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DetailDesc = "Perfectly balanced 58mm tamper to ensure an even and consistent espresso puck.",
                            Name = "Espresso Tamper (58mm)",
                            ShortDesc = "Solid stainless steel tamper with ergonomic handle.",
                            Slug = "espresso-tamper-58mm",
                            Status = "active",
                            StockQty = 20,
                            ThumbnailUrl = "/images/category-accessories.png",
                            UpdatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 26
                        });
                });

            modelBuilder.Entity("BanCaPheNuocGiaiKhat.Models.Entities.ProductImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("image_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("alt_text");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("url");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("product_images", (string)null);
                });

            modelBuilder.Entity("BanCaPheNuocGiaiKhat.Models.Entities.Role", b =>
                {
                    b.Property<byte>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = (byte)1,
                            Description = "Quản trị viên hệ thống, toàn quyền.",
                            RoleName = "admin"
                        },
                        new
                        {
                            RoleId = (byte)2,
                            Description = "Nhân viên, quản lý đơn hàng và sản phẩm.",
                            RoleName = "staff"
                        },
                        new
                        {
                            RoleId = (byte)3,
                            Description = "Khách hàng đăng ký tài khoản mua hàng.",
                            RoleName = "customer"
                        });
                });

            modelBuilder.Entity("BanCaPheNuocGiaiKhat.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("address");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FacebookId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("facebook_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("google_id");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phone");

                    b.Property<byte>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)3)
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FacebookId")
                        .IsUnique()
                        .HasFilter("[facebook_id] IS NOT NULL");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("[google_id] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BanCaPheNuocGiaiKhat.Models.Entities.Category", b =>
                {
                    b.HasOne("BanCaPheNuocGiaiKhat.Models.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BanCaPheNuocGiaiKhat.Models.Entities.Invoice", b =>
                {
                    b.HasOne("BanCaPheNuocGiaiKhat.Models.Entities.Order", "Order")
                        .WithOne("Invoice")
                        .HasForeignKey("BanCaPheNuocGiaiKhat.Models.Entities.Invoice", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BanCaPheNuocGiaiKhat.Models.Entities.Order", b =>
                {
                    b.HasOne("BanCaPheNuocGiaiKhat.Models.Entities.User", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("BanCaPheNuocGiaiKhat.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("BanCaPheNuocGiaiKhat.Models.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanCaPheNuocGiaiKhat.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BanCaPheNuocGiaiKhat.Models.Entities.Product", b =>
                {
                    b.HasOne("BanCaPheNuocGiaiKhat.Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BanCaPheNuocGiaiKhat.Models.Entities.ProductImage", b =>
                {
                    b.HasOne("BanCaPheNuocGiaiKhat.Models.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BanCaPheNuocGiaiKhat.Models.Entities.User", b =>
                {
                    b.HasOne("BanCaPheNuocGiaiKhat.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BanCaPheNuocGiaiKhat.Models.Entities.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("BanCaPheNuocGiaiKhat.Models.Entities.Order", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BanCaPheNuocGiaiKhat.Models.Entities.Product", b =>
                {
                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("BanCaPheNuocGiaiKhat.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
